/**
 * Methodology: the real coverage-gate report, the agent workflow's
 * research reports with verification status, and the honest-limitations
 * section. Server component — the coverage report is a build-time
 * artifact generated by `npm run coverage:report` (ppi_core.simulate).
 */

import coverageReport from "@/data/coverage-report.json";
import { runWorkflow } from "@/lib/agents/orchestrator";
import { DEFAULT_RUBRIC } from "@/lib/rubrics/rubrics";

export const dynamic = "force-static";

interface CoverageRow {
  coverage: number;
  coverage_per_coord?: number[];
  mean_width: number;
  reps: number;
}

interface CoverageReport {
  seed: number;
  nominal_level: number;
  min_coverage_gate: number;
  pass: boolean;
  failures: string[];
  scenarios: Record<string, Record<string, CoverageRow>>;
}

const report = coverageReport as unknown as CoverageReport;

const UNGATED = new Set([
  "active_ipw_mean.ppi_naive",
  "policy_gain.random",
  "policy_gain.uncertainty",
  "policy_gain.variance_reduction",
  "policy_gain.diversity",
]);

export default async function MethodologyPage() {
  // Research reports come from the live agent pipeline over fixtures —
  // computed at build/render time, verification recomputed independently.
  const wf = await runWorkflow({
    feedIds: ["ms", "ut", "mo", "ky"],
    mode: "fixture",
    estimand: "duration_days",
    oracle: "heuristic",
  });

  return (
    <main className="flex max-w-[900px] flex-col gap-6">
      <h1 className="text-[28px] font-semibold tracking-tight">Methodology</h1>

      <section aria-labelledby="coverage-h">
        <h2 id="coverage-h" className="mb-2 text-[20px] font-medium">
          Coverage gate
        </h2>
        <p className="mb-2 text-[14px]" style={{ color: "var(--ink-2)" }}>
          Every interval this engine produces is simulation-tested at known ground truth: nominal
          95% intervals must cover at least {report.min_coverage_gate * 100}% empirically or the
          build fails. Generated by <code>ppi_core.simulate</code>, seed{" "}
          <span className="num">{report.seed}</span>, byte-identical on rerun. Status:{" "}
          {report.pass ? (
            <span style={{ color: "var(--status-good)" }}>✓ PASS (zero failures)</span>
          ) : (
            <span style={{ color: "var(--status-bad)" }}>
              ✗ FAILING: {report.failures.join("; ")}
            </span>
          )}
        </p>
        <div className="panel overflow-x-auto">
          <table className="w-full text-[13px]">
            <thead>
              <tr className="text-left text-[12px]" style={{ color: "var(--ink-2)" }}>
                <th className="p-2">Scenario · method</th>
                <th className="p-2 text-right">Coverage</th>
                <th className="p-2 text-right">Mean width</th>
                <th className="p-2 text-right">Reps</th>
                <th className="p-2">Status</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(report.scenarios).flatMap(([scen, methods]) =>
                Object.entries(methods).map(([method, row]) => {
                  const key = `${scen}.${method}`;
                  const ungated = UNGATED.has(key);
                  const ok = row.coverage >= report.min_coverage_gate;
                  return (
                    <tr key={key} className="border-t" style={{ borderColor: "var(--edge)" }}>
                      <td className="num p-2">{key}</td>
                      <td className="num p-2 text-right">
                        {row.coverage.toFixed(4)}
                        {row.coverage_per_coord
                          ? ` (per-coord min of [${row.coverage_per_coord.join(", ")}])`
                          : ""}
                      </td>
                      <td className="num p-2 text-right">{row.mean_width.toFixed(4)}</td>
                      <td className="num p-2 text-right">{row.reps}</td>
                      <td className="p-2">
                        {ungated ? (
                          <span className="chip" title="Reported, not gated">
                            ungated
                          </span>
                        ) : ok ? (
                          <span style={{ color: "var(--status-good)" }}>✓ pass</span>
                        ) : (
                          <span style={{ color: "var(--status-bad)" }}>✗ fail</span>
                        )}
                      </td>
                    </tr>
                  );
                }),
              )}
            </tbody>
          </table>
        </div>
        <p className="mt-1 text-[12px]" style={{ color: "var(--ink-3)" }}>
          active_ipw_mean.ppi_naive is a deliberate demonstration of the selection-bias trap (0%
          coverage without IPW correction); policy_gain rows are a width-efficiency experiment whose
          coverage is gated separately at higher replication counts.
        </p>
      </section>

      <section aria-labelledby="research-h">
        <h2 id="research-h" className="mb-2 text-[20px] font-medium">
          Agency research reports
        </h2>
        <p className="mb-2 text-[14px]" style={{ color: "var(--ink-2)" }}>
          The research agent scores each agency&apos;s published feed against the versioned rubric{" "}
          <span className="num">
            {DEFAULT_RUBRIC.id} v{DEFAULT_RUBRIC.version}
          </span>
          ; the verification agent independently recomputes every finding and refuses anything it
          cannot ground. Fixture snapshots of 2026-08-16.
        </p>
        <div className="grid gap-3 md:grid-cols-2">
          {wf.research.map((r) => {
            const verification = wf.researchVerification.find((v) => v.reportOf === r.feedId);
            return (
              <div key={r.feedId} className="panel p-3">
                <div className="mb-1 flex items-center justify-between">
                  <h3 className="text-[16px] font-medium">{r.agency}</h3>
                  <span
                    className="chip"
                    style={{
                      color: verification?.allPassed ? "var(--status-good)" : "var(--status-bad)",
                    }}
                  >
                    {verification?.allPassed ? "✓ verified" : "✗ verification failed"}
                  </span>
                </div>
                <div className="num mb-2 text-[24px]">
                  {(r.overallScore * 100).toFixed(1)}
                  <span className="text-[13px]" style={{ color: "var(--ink-2)" }}>
                    {" "}
                    / 100 · {r.recordCount} records
                  </span>
                </div>
                <table className="w-full text-[12px]">
                  <tbody>
                    {r.findings.map((f) => (
                      <tr key={f.criterionId}>
                        <td className="py-0.5">{f.criterionId}</td>
                        <td className="num py-0.5 text-right">
                          {f.numerator}/{f.denominator} = {(f.score * 100).toFixed(1)}%
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            );
          })}
        </div>
      </section>

      <section aria-labelledby="limits-h">
        <h2 id="limits-h" className="mb-2 text-[20px] font-medium">
          Known limitations (stated, not hidden)
        </h2>
        <ul className="flex list-disc flex-col gap-2 pl-5 text-[14px]">
          <li>
            <strong>Plug-in selection weights.</strong> Multi-round adaptive selection uses realized
            cumulative inclusion probabilities; exact Horvitz–Thompson unbiasedness does not hold
            under adaptive designs. The scheme is certified empirically by gated end-to-end
            simulations, including asymmetric-uncertainty designs built to stress it
            (docs/gauntlet/statistical-core.md).
          </li>
          <li>
            <strong>Two interval targets.</strong> Analytic CIs target the superpopulation; the
            runner&apos;s bootstrap targets the mean of the ingested pool (selection uncertainty
            only). They are labeled distinctly everywhere and answer different questions.
          </li>
          <li>
            <strong>Policy gains depend on the oracle.</strong> Active policies beat random by ~6%
            width in the gated experiment because oracle uncertainty is informative there; with an
            uninformative oracle they degrade to random. The random baseline is always available for
            comparison.
          </li>
          <li>
            <strong>Label budget semantics.</strong> Ground-truth labels derive from authoritative
            feed fields via the verification agent; the budget simulates real-world acquisition cost
            rather than paying it (docs/02-feeds.md).
          </li>
          <li>
            <strong>The heuristic oracle is weak by design</strong> and labeled as such
            (`heuristic:v1`); live Anthropic labeling requires an API key and is tagged with its
            model identity.
          </li>
          <li>
            <strong>Determinism is certified single-platform</strong> (byte-identical reruns on the
            build machine and CI image; cross-platform BLAS bit-identity is not claimed).
          </li>
          <li>
            <strong>lane_restricted covers MS + MO only</strong> — Utah and Kentucky publish
            vehicle_impact as &quot;unknown&quot; on every record in our snapshots, so the verifier
            refuses them for that estimand (516 of 1,802 records eligible).
          </li>
        </ul>
      </section>
    </main>
  );
}
